title: Kai Xiang 向凯
description: Feel AGI, embrace AGI and build AGI.
url: https://kaimit.github.io
baseurl: ""
permalink: /:title/
github_username: kaimit
linkedin_username: mitkaixiang
twitter_username: xiang_kai_MIT
email: xiangk07@gmail.com
googlescholar: vDtcytEAAAAJ

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed